import _MyToast from "./MyToast";
import _MyNetInfo from "./MyNetInfo";
import _Login from "./Login";
import _Welcome from "./Welcome";
import _Signup from "./Signup";
import _Home from "./Home";
import _Map from "./Map";
import _ProductDetail from "./ProductDetail";
import _UserProfile from "./UserProfile";
import _EditProfile from "./EditProfile";
import _SaveProfile from "./SaveProfile";
import _Search from "./Search";
import _Cart from "./Cart";

export const Cart = _Cart;
export const Search = _Search;
export const SaveProfile = _SaveProfile;
export const EditProfile = _EditProfile;
export const UserProfile = _UserProfile;
export const ProductDetail = _ProductDetail;
export const Map = _Map;
export const Home = _Home;
export const Signup = _Signup;
export const Welcome = _Welcome;
export const Login = _Login;
export const MyNetInfo = _MyNetInfo;
export const MyToast = _MyToast;
